INSERT INTO Course(ID, NAME) VALUES(10001, 'JPA & Hibernate');
INSERT INTO Course(ID, NAME) VALUES(10002, 'Core Java');
INSERT INTO Course(ID, NAME) VALUES(10003, 'Spring Boot');
INSERT INTO Course(ID, NAME) VALUES(10004, 'CSS');
INSERT INTO Course(ID, NAME) VALUES(10005, 'Angular');
INSERT INTO Course(ID, NAME) VALUES(10006, 'JSP');